
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

#plugin 'cocoapods-binary'
# all_binary!

use_frameworks!
inhibit_all_warnings!

install! 'cocoapods',
disable_input_output_paths: true,
generate_multiple_pod_projects: true

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = false
            config.build_settings['ARCHS'] = 'arm64 arm64e armv7s'
            config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
    
    installer.pods_project.root_object.known_regions = ["Base", "en"]
    installer.pods_project.root_object.development_region = "en"
end

targetsArray = ['VueIOS']

targetsArray.each do |t|
  target t do
    pod 'AFNetworking', '~> 3.2.1'
    pod 'SDWebImage', '~> 5.1.1'
    pod 'MBProgressHUD'
    pod 'SAMKeychain'
    pod 'HMSegmentedControl'
    pod 'FMDB'
    pod 'MJRefresh','~> 3.1.15.7'
    pod 'MMPopupView'
    pod 'MJExtension'
    pod 'IQKeyboardManager', '~> 6.5.0'
    pod 'YBAttributeTextTapAction', '~> 3.0.3'
    pod 'Reachability', '~> 3.2'
    pod 'SSZipArchive', '~> 1.8.1'
    pod 'CocoaLumberjack', '~> 3.6.0'
    pod 'TZImagePickerController', '~> 3.2.7'
    pod 'Toast', '~> 4.0.0'
    pod 'SZJPickerView', '~> 1.0.7'
    pod 'SPGDatePicker', '~> 2.6.8.2'
    pod 'UITextView+Placeholder', :git => 'https://github.com/devxoul/UITextView-Placeholder.git'
    pod 'CMPopTipView', '~> 2.3.2'
    pod 'YYImage', '~> 1.0.4'
    pod 'YBImageBrowser'
    pod 'YBImageBrowser/Video'
    #pod 'YYImage/WebP'
    pod 'YYCache', '~> 1.0.4'
    pod 'LYEmptyView', '~> 1.3.1'
    pod 'PureLayout', '~> 3.1.5'
    pod 'FSCalendar', '~> 2.8.0'
    pod 'SPAlertController', '~> 3.1.0'
    pod 'SYeeBadgeView', '~> 0.0.3'
    pod 'WSLWaterFlowLayout', '~> 1.0.1'
    pod 'FLAnimatedImage', '~> 1.0.12'
    pod 'DateTools'
  end
end

